export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore",
        "revert",
      ],
    ],
    "scope-enum": [
      1,
      "always",
      [
        "schemas",
        "catalog-core",
        "tokens",
        "components",
        "motion",
        "three-d",
        "compositions",
        "registry-builder",
        "mcp-core",
        "cli",
        "conformance",
        "telemetry",
        "self-hosting",
        "release-policy",
        "public-api",
        "hosted-gateway",
        "docs",
        "deps",
        "ci",
      ],
    ],
    "subject-case": [2, "never", ["sentence-case", "start-case", "pascal-case", "upper-case"]],
    "header-max-length": [2, "always", 100],
  },
};
